# Generated by Django 4.2.4 on 2023-12-02 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.AddField(
            model_name='endereco',
            name='endereco_padrao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='especie',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_especies/'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('SC', 'Santa Catarina'), ('PR', 'Paraná'), ('PB', 'Paraíba'), ('RS', 'Rio Grande do Sul'), ('MG', 'Minas Gerais'), ('AP', 'Amapá'), ('ES', 'Espirito Santo'), ('RO', 'Rondônia'), ('AL', 'Alagoas'), ('PE', 'Pernambuco'), ('MS', 'Mato Grosso do Sul'), ('GO', 'Goiás'), ('SP', 'São Paulo'), ('TO', 'Tocantins'), ('AM', 'Amazonas'), ('RR', 'Roraima'), ('AC', 'Acre'), ('MA', 'Maranhão'), ('CE', 'Ceará'), ('SE', 'Sergipe'), ('MT', 'Mato Grosso'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('PI', 'Piauí'), ('BA', 'Bahia'), ('DF', 'Distrito Federal')], default='MG', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AG', 'Aguardando Pagamento'), ('PEN', 'Pedido entregue'), ('PE', 'Pedido enviado'), ('PC', 'Pagamento Confirmado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='nome',
            field=models.CharField(choices=[('AG', 'Aguardando Pagamento'), ('PEN', 'Pedido entregue'), ('PE', 'Pedido enviado'), ('PC', 'Pagamento Confirmado')], default='AG', max_length=3),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.cliente')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.endereco')),
                ('itens', models.ManyToManyField(to='aplic.itempedido')),
            ],
        ),
    ]
