# Generated by Django 4.2.4 on 2023-12-05 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='codigo',
        ),
        migrations.AddField(
            model_name='avaliacaocategoria',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='endereco',
            name='endereco_padrao',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='especie',
            name='Planta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplic.planta'),
        ),
        migrations.AddField(
            model_name='especie',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_especies/'),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_pedido',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('TO', 'Tocantins'), ('ES', 'Espirito Santo'), ('SE', 'Sergipe'), ('PE', 'Pernambuco'), ('RJ', 'Rio de Janeiro'), ('AL', 'Alagoas'), ('BA', 'Bahia'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('PB', 'Paraíba'), ('PI', 'Piauí'), ('AP', 'Amapá'), ('PR', 'Paraná'), ('MG', 'Minas Gerais'), ('RR', 'Roraima'), ('SP', 'São Paulo'), ('DF', 'Distrito Federal'), ('MS', 'Mato Grosso do Sul'), ('GO', 'Goiás'), ('AC', 'Acre'), ('MT', 'Mato Grosso'), ('AM', 'Amazonas'), ('CE', 'Ceará'), ('MA', 'Maranhão'), ('SC', 'Santa Catarina')], default='MG', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PE', 'Pedido enviado'), ('PEN', 'Pedido entregue'), ('PC', 'Pagamento Confirmado'), ('AG', 'Aguardando Pagamento')], max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='nome',
            field=models.CharField(choices=[('PE', 'Pedido enviado'), ('PEN', 'Pedido entregue'), ('PC', 'Pagamento Confirmado'), ('AG', 'Aguardando Pagamento')], default='AG', max_length=3),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('metodo_pagamento', models.CharField(choices=[('cartao_credito', 'Cartão de crédito'), ('pix', 'PIX')], default='PIX', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplic.cliente')),
                ('endereco', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.endereco')),
                ('itens', models.ManyToManyField(to='aplic.itempedido')),
            ],
        ),
    ]
