# Generated by Django 4.0.1 on 2023-10-10 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('cliente', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('data_hora', models.FloatField()),
            ],
        ),
    ]
