# Generated by Django 4.2.6 on 2023-12-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0002_alter_endereco_estado_alter_pedido_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorias',
            name='cultivo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='categorias',
            name='manutencao',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('RR', 'Roraima'), ('MG', 'Minas Gerais'), ('AC', 'Acre'), ('MS', 'Mato Grosso do Sul'), ('SE', 'Sergipe'), ('PR', 'Paraná'), ('MA', 'Maranhão'), ('RS', 'Rio Grande do Sul'), ('CE', 'Ceará'), ('SP', 'São Paulo'), ('ES', 'Espirito Santo'), ('PB', 'Paraíba'), ('SC', 'Santa Catarina'), ('BA', 'Bahia'), ('AP', 'Amapá'), ('RO', 'Rondônia'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('GO', 'Goiás'), ('RN', 'Rio Grande do Norte'), ('MT', 'Mato Grosso'), ('RJ', 'Rio de Janeiro'), ('PI', 'Piauí'), ('PE', 'Pernambuco'), ('TO', 'Tocantins'), ('DF', 'Distrito Federal')], default='MG', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PE', 'Pedido enviado'), ('AG', 'Aguardando Pagamento'), ('PC', 'Pagamento Confirmado'), ('PEN', 'Pedido entregue')], max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='nome',
            field=models.CharField(choices=[('PE', 'Pedido enviado'), ('AG', 'Aguardando Pagamento'), ('PC', 'Pagamento Confirmado'), ('PEN', 'Pedido entregue')], default='AG', max_length=3),
        ),
    ]
