# Generated by Django 4.2.4 on 2023-12-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_avaliacaocategoria_cliente_alter_endereco_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='metodo_pagamento',
            field=models.CharField(choices=[('cartao_credito', 'Cartão de crédito'), ('pix', 'PIX')], default='PIX', max_length=20),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('PI', 'Piauí'), ('MT', 'Mato Grosso'), ('AM', 'Amazonas'), ('RJ', 'Rio de Janeiro'), ('MA', 'Maranhão'), ('AP', 'Amapá'), ('CE', 'Ceará'), ('PE', 'Pernambuco'), ('RS', 'Rio Grande do Sul'), ('SP', 'São Paulo'), ('ES', 'Espirito Santo'), ('AL', 'Alagoas'), ('PB', 'Paraíba'), ('BA', 'Bahia'), ('GO', 'Goiás'), ('PR', 'Paraná'), ('RN', 'Rio Grande do Norte'), ('TO', 'Tocantins'), ('RO', 'Rondônia'), ('MS', 'Mato Grosso do Sul'), ('SC', 'Santa Catarina'), ('RR', 'Roraima'), ('SE', 'Sergipe'), ('MG', 'Minas Gerais'), ('AC', 'Acre'), ('DF', 'Distrito Federal')], default='MG', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AG', 'Aguardando Pagamento'), ('PEN', 'Pedido entregue'), ('PE', 'Pedido enviado'), ('PC', 'Pagamento Confirmado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='nome',
            field=models.CharField(choices=[('AG', 'Aguardando Pagamento'), ('PEN', 'Pedido entregue'), ('PE', 'Pedido enviado'), ('PC', 'Pagamento Confirmado')], default='AG', max_length=3),
        ),
    ]
