# Generated by Django 4.2.6 on 2023-12-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_alter_categorias_cultivo_alter_categorias_manutencao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('ES', 'Espirito Santo'), ('AM', 'Amazonas'), ('RN', 'Rio Grande do Norte'), ('MS', 'Mato Grosso do Sul'), ('SP', 'São Paulo'), ('MA', 'Maranhão'), ('PE', 'Pernambuco'), ('AC', 'Acre'), ('CE', 'Ceará'), ('MT', 'Mato Grosso'), ('AL', 'Alagoas'), ('RJ', 'Rio de Janeiro'), ('PB', 'Paraíba'), ('MG', 'Minas Gerais'), ('SE', 'Sergipe'), ('PR', 'Paraná'), ('BA', 'Bahia'), ('GO', 'Goiás'), ('DF', 'Distrito Federal'), ('AP', 'Amapá'), ('PI', 'Piauí'), ('TO', 'Tocantins'), ('RO', 'Rondônia'), ('RR', 'Roraima')], default='MG', max_length=200),
        ),
        migrations.AlterField(
            model_name='especie',
            name='Categoria_Botânica',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='especie',
            name='Necessidades_de_Luz',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='especie',
            name='Usos_da_Espécie',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='especie',
            name='descrição',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('AG', 'Aguardando Pagamento'), ('PE', 'Pedido enviado'), ('PC', 'Pagamento Confirmado'), ('PEN', 'Pedido entregue')], max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='nome',
            field=models.CharField(choices=[('AG', 'Aguardando Pagamento'), ('PE', 'Pedido enviado'), ('PC', 'Pagamento Confirmado'), ('PEN', 'Pedido entregue')], default='AG', max_length=3),
        ),
    ]
