# Generated by Django 4.2.4 on 2023-12-05 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_compra_metodo_pagamento_alter_endereco_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='Planta',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='aplic.planta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('PE', 'Pernambuco'), ('AP', 'Amapá'), ('PB', 'Paraíba'), ('MS', 'Mato Grosso do Sul'), ('ES', 'Espirito Santo'), ('MA', 'Maranhão'), ('AL', 'Alagoas'), ('DF', 'Distrito Federal'), ('GO', 'Goiás'), ('RR', 'Roraima'), ('MT', 'Mato Grosso'), ('SE', 'Sergipe'), ('AM', 'Amazonas'), ('MG', 'Minas Gerais'), ('PI', 'Piauí'), ('TO', 'Tocantins'), ('AC', 'Acre'), ('PR', 'Paraná'), ('SP', 'São Paulo'), ('RJ', 'Rio de Janeiro'), ('CE', 'Ceará'), ('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('BA', 'Bahia')], default='MG', max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pedido entregue'), ('PE', 'Pedido enviado'), ('PC', 'Pagamento Confirmado'), ('AG', 'Aguardando Pagamento')], max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='nome',
            field=models.CharField(choices=[('PEN', 'Pedido entregue'), ('PE', 'Pedido enviado'), ('PC', 'Pagamento Confirmado'), ('AG', 'Aguardando Pagamento')], default='AG', max_length=3),
        ),
    ]
