# Generated by Django 4.2.6 on 2023-12-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_alter_endereco_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(choices=[('MS', 'Mato Grosso do Sul'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('RO', 'Rondônia'), ('AP', 'Amapá'), ('PR', 'Paraná'), ('BA', 'Bahia'), ('GO', 'Goiás'), ('AL', 'Alagoas'), ('ES', 'Espirito Santo'), ('TO', 'Tocantins'), ('AM', 'Amazonas'), ('MG', 'Minas Gerais'), ('PB', 'Paraíba'), ('DF', 'Distrito Federal'), ('PI', 'Piauí'), ('RS', 'Rio Grande do Sul'), ('SP', 'São Paulo'), ('SC', 'Santa Catarina'), ('CE', 'Ceará'), ('RJ', 'Rio de Janeiro'), ('PE', 'Pernambuco'), ('RR', 'Roraima'), ('AC', 'Acre'), ('RN', 'Rio Grande do Norte'), ('SE', 'Sergipe')], default='MG', max_length=200),
        ),
        migrations.AlterField(
            model_name='planta',
            name='cuidados',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='planta',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
    ]
