# Generated by Django 4.0.1 on 2023-10-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_itempedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preço', models.FloatField()),
                ('descrição', models.CharField(max_length=100)),
            ],
        ),
    ]
